# theme: jekyll-theme-leap-day
title: Spotify
description: Advanced music streaming platform.
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
